name: Run tests

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    with:
      additional-python-dependencies: llama-cpp-python huggingface-hub cryptography
      clone-repo: true
