name: Test with ezlocalai
on:
  workflow_call:
    inputs:
      notebook:
        type: string
        description: file to run (ending in .ipynb), can be directory to batch run (without trailing slash)
        default: "tests.ipynb"
      port-mapping:
        type: string
      image-options:
        type: string
        description: like --entrypoint, --command
      additional-python-dependencies:
        type: string
        description: add whatever pip you need here
      additional-args:
        type: string
        description: additional args for nbconvert
        default: "--log-level DEBUG"
      append-logs:
        type: boolean
        default: false
      clone-repo:
        type: boolean
        default: true
jobs:
  jupyter-test-job:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.dockerBuild.outputs.digest }}

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - name: Install jupyter
        run: pip3 install jupyter nbconvert[webpdf]
      - name: Update package lists and install jupyter output generation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --fix-missing -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Clone repository and install package
        if: inputs.clone-repo
        run: |
          git clone https://github.com/${{ github.repository }} /tmp/repo
          cd /tmp/repo
          pip3 install .

      - name: Install additional dependencies for notebooks
        if: inputs.additional-python-dependencies
        run: pip3 install requests ${{ inputs.additional-python-dependencies }}

      - name: Set notebook and artifact files
        run: |
          notebook="${{ inputs.notebook }}"
          if ${{ endsWith( inputs.notebook, 'ipynb' ) }} ; then
            echo "notebook-file=${notebook}" >> "$GITHUB_ENV"
            echo "artifact-file=${notebook%.*}.pdf"  >> "$GITHUB_ENV"
          else 
            echo "notebook-file=${notebook}/*.ipynb" >> "$GITHUB_ENV"
            echo "artifact-file=${notebook}/*.pdf"  >> "$GITHUB_ENV"
          fi

      - name: Execute notebook
        run: python3 -m nbconvert --execute --log-level DEBUG --to pdf  ${{ env.notebook-file }}

      - name: Append test logs
        if: inputs.append-logs
        run: |
          echo "artifact-file=${{ env.artifact-file }}\n/test-output.log" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ${{ env.artifact-file }}